import type { LanguageCode } from "@/context/language-context";

const translations: Record<string, Record<LanguageCode, string>> = {
  // ── Navigation ──────────────────────────────────────────────
  "nav.home":       { en: "Home",      zh: "首页",     hi: "होम",     es: "Inicio",     fr: "Accueil",    ar: "الرئيسية",   bn: "হোম",      pt: "Início",     ru: "Главная",    ja: "ホーム" },
  "nav.about":      { en: "About",     zh: "关于",     hi: "परिचय",    es: "Nosotros",   fr: "À propos",   ar: "من نحن",     bn: "সম্পর্কে",    pt: "Sobre",      ru: "О нас",      ja: "概要" },
  "nav.solutions":  { en: "Solutions", zh: "解决方案",  hi: "समाधान",    es: "Soluciones", fr: "Solutions",  ar: "الحلول",     bn: "সমাধান",     pt: "Soluções",   ru: "Решения",    ja: "ソリューション" },
  "nav.news":       { en: "News",      zh: "新闻",     hi: "समाचार",    es: "Noticias",   fr: "Actualités", ar: "الأخبار",    bn: "সংবাদ",      pt: "Notícias",   ru: "Новости",    ja: "ニュース" },
  "nav.learn":      { en: "Learn",     zh: "学习",     hi: "सीखें",     es: "Aprender",   fr: "Apprendre",  ar: "تعلّم",       bn: "শিখুন",      pt: "Aprender",   ru: "Обучение",   ja: "ラーニング" },
  "nav.insights":   { en: "Insights",  zh: "洞察",      hi: "अंतर्दृष्टि", es: "Perspectivas", fr: "Perspectives", ar: "رؤى",         bn: "অন্তর্দৃষ্টি",  pt: "Insights",    ru: "Аналитика",   ja: "インサイト" },
  "nav.faqs":       { en: "FAQs",      zh: "常见问题",  hi: "अक्सर पूछे जाने वाले प्रश्न", es: "Preguntas frecuentes", fr: "FAQ", ar: "الأسئلة الشائعة", bn: "প্রায়শই জিজ্ঞাসিত প্রশ্ন", pt: "Perguntas frequentes", ru: "Вопросы", ja: "よくある質問" },

  // ── Header ──────────────────────────────────────────────────
  "header.getInTouch":     { en: "Get In Touch",       zh: "联系我们",         hi: "संपर्क करें",        es: "Contáctenos",        fr: "Contactez-nous",    ar: "تواصل معنا",       bn: "যোগাযোগ করুন",       pt: "Entre em contato",   ru: "Связаться",          ja: "お問い合わせ" },
  "header.searchPlaceholder": { en: "Search the site...", zh: "搜索网站...",      hi: "साइट खोजें...",      es: "Buscar en el sitio...", fr: "Rechercher...",   ar: "ابحث في الموقع...",  bn: "সাইট অনুসন্ধান...",    pt: "Pesquisar no site...", ru: "Поиск по сайту...",  ja: "サイトを検索..." },
  "header.noResults":      { en: "No results found",   zh: "未找到结果",        hi: "कोई परिणाम नहीं",    es: "No se encontraron resultados", fr: "Aucun résultat", ar: "لا توجد نتائج", bn: "কোন ফলাফল পাওয়া যায়নি", pt: "Nenhum resultado", ru: "Ничего не найдено",  ja: "結果が見つかりません" },
  "header.tryDifferent":   { en: "Try a different search term", zh: "尝试不同的搜索词", hi: "कोई अन्य खोज शब्द आज़माएं", es: "Pruebe otro término", fr: "Essayez un autre terme", ar: "جرّب مصطلحًا مختلفًا", bn: "অন্য শব্দ দিয়ে চেষ্টা করুন", pt: "Tente outro termo", ru: "Попробуйте другой запрос", ja: "別の検索語をお試しください" },

  // ── Footer ──────────────────────────────────────────────────
  "footer.description":    { en: "The Attention Technology Company. Since 2013, we've been powering attention-first advertising with predictive eye-tracking technology.", zh: "注意力科技公司。自2013年以来，我们一直通过预测性眼动追踪技术推动注意力优先的广告。", hi: "अटेंशन टेक्नोलॉजी कंपनी। 2013 से, हम भविष्यवाणी आई-ट्रैकिंग तकनीक के साथ ध्यान-प्रथम विज्ञापन को शक्ति प्रदान कर रहे हैं।", es: "La Empresa de Tecnología de Atención. Desde 2013, impulsamos la publicidad basada en atención con tecnología predictiva de seguimiento ocular.", fr: "L'entreprise de technologie de l'attention. Depuis 2013, nous alimentons la publicité axée sur l'attention grâce à la technologie prédictive de suivi oculaire.", ar: "شركة تكنولوجيا الانتباه. منذ 2013، نقدم إعلانات قائمة على الانتباه باستخدام تقنية تتبع العين التنبؤية.", bn: "অ্যাটেনশন টেকনোলজি কোম্পানি। ২০১৩ সাল থেকে, আমরা পূর্বাভাসমূলক আই-ট্র্যাকিং প্রযুক্তি দিয়ে মনোযোগ-ভিত্তিক বিজ্ঞাপনকে শক্তিশালী করছি।", pt: "A Empresa de Tecnologia de Atenção. Desde 2013, impulsionamos publicidade baseada em atenção com tecnologia preditiva de rastreamento ocular.", ru: "Компания технологий внимания. С 2013 года мы развиваем рекламу, ориентированную на внимание, с помощью предиктивной технологии отслеживания взгляда.", ja: "アテンション・テクノロジー・カンパニー。2013年以来、予測的アイトラッキング技術でアテンション・ファースト広告を推進しています。" },
  "footer.navigation":     { en: "Navigation",       zh: "导航",         hi: "नेविगेशन",       es: "Navegación",      fr: "Navigation",     ar: "التنقل",        bn: "নেভিগেশন",       pt: "Navegação",      ru: "Навигация",      ja: "ナビゲーション" },
  "footer.company":        { en: "Company",          zh: "公司",         hi: "कंपनी",          es: "Empresa",         fr: "Entreprise",     ar: "الشركة",        bn: "কোম্পানি",       pt: "Empresa",        ru: "Компания",       ja: "会社情報" },
  "footer.careers":        { en: "Careers",          zh: "职业",         hi: "करियर",          es: "Carreras",        fr: "Carrières",      ar: "وظائف",         bn: "ক্যারিয়ার",      pt: "Carreiras",      ru: "Карьера",        ja: "採用情報" },
  "footer.privacyPolicy":  { en: "Privacy Policy",   zh: "隐私政策",      hi: "गोपनीयता नीति",   es: "Política de privacidad", fr: "Politique de confidentialité", ar: "سياسة الخصوصية", bn: "গোপনীয়তা নীতি", pt: "Política de privacidade", ru: "Политика конфиденциальности", ja: "プライバシーポリシー" },
  "footer.termsOfService": { en: "Terms of Service", zh: "服务条款",      hi: "सेवा की शर्तें",   es: "Términos de servicio", fr: "Conditions d'utilisation", ar: "شروط الخدمة",   bn: "পরিষেবার শর্তাবলী", pt: "Termos de serviço", ru: "Условия использования", ja: "利用規約" },
  "footer.contentManager": { en: "Content Manager",  zh: "内容管理",      hi: "सामग्री प्रबंधक",  es: "Gestor de contenido", fr: "Gestionnaire de contenu", ar: "مدير المحتوى",  bn: "কন্টেন্ট ম্যানেজার", pt: "Gerenciador de conteúdo", ru: "Менеджер контента", ja: "コンテンツマネージャー" },
  "footer.copyright":      { en: "Lumen Research. All rights reserved.", zh: "Lumen Research。保留所有权利。", hi: "Lumen Research। सर्वाधिकार सुरक्षित।", es: "Lumen Research. Todos los derechos reservados.", fr: "Lumen Research. Tous droits réservés.", ar: "Lumen Research. جميع الحقوق محفوظة.", bn: "Lumen Research। সমস্ত অধিকার সংরক্ষিত।", pt: "Lumen Research. Todos os direitos reservados.", ru: "Lumen Research. Все права защищены.", ja: "Lumen Research. All rights reserved." },

  // ── Homepage: Hero ──────────────────────────────────────────
  "home.heroTitle":        { en: "Attention into",    zh: "注意力转化为",   hi: "ध्यान को बदलें",   es: "Atención en",     fr: "L'attention en",  ar: "الانتباه إلى",   bn: "মনোযোগকে রূপান্তর", pt: "Atenção em",     ru: "Внимание в",     ja: "アテンションを" },
  "home.rotatingWord.profit": { en: "profit",          zh: "利润",          hi: "लाभ",             es: "ganancias",       fr: "profit",          ar: "ربح",            bn: "মুনাফা",          pt: "lucro",          ru: "прибыль",        ja: "利益" },
  "home.rotatingWord.sales":  { en: "sales",           zh: "销售",          hi: "बिक्री",           es: "ventas",          fr: "ventes",          ar: "مبيعات",          bn: "বিক্রয়",          pt: "vendas",         ru: "продажи",        ja: "売上" },
  "home.rotatingWord.action": { en: "action",          zh: "行动",          hi: "कार्रवाई",         es: "acción",          fr: "action",          ar: "عمل",            bn: "কর্ম",            pt: "ação",           ru: "действие",       ja: "アクション" },
  "home.rotatingWord.memory": { en: "memory",          zh: "记忆",          hi: "स्मृति",           es: "recuerdo",        fr: "mémoire",         ar: "ذاكرة",           bn: "স্মৃতি",           pt: "memória",        ru: "память",         ja: "記憶" },
  "home.rotatingWord.choice": { en: "choice",          zh: "选择",          hi: "चयन",             es: "elección",        fr: "choix",           ar: "اختيار",          bn: "পছন্দ",           pt: "escolha",        ru: "выбор",          ja: "選択" },
  "home.learnMore":        { en: "Learn More",       zh: "了解更多",      hi: "और जानें",        es: "Más información", fr: "En savoir plus",  ar: "اعرف المزيد",    bn: "আরও জানুন",      pt: "Saiba mais",     ru: "Узнать больше",  ja: "詳しく見る" },

  // ── Homepage: Latest News ───────────────────────────────────
  "home.latestNews":       { en: "Latest Insights",  zh: "最新洞察",      hi: "नवीनतम अंतर्दृष्टि", es: "Últimas perspectivas", fr: "Dernières perspectives", ar: "أحدث الرؤى", bn: "সর্বশেষ অন্তর্দৃষ্টি", pt: "Últimas perspectivas", ru: "Последние аналитические материалы", ja: "最新インサイト" },
  "home.loadingNews":      { en: "Loading latest news…", zh: "正在加载最新新闻…", hi: "नवीनतम समाचार लोड हो रहे हैं…", es: "Cargando últimas noticias…", fr: "Chargement des dernières nouvelles…", ar: "جارٍ تحميل آخر الأخبار…", bn: "সর্বশেষ সংবাদ লোড হচ্ছে…", pt: "Carregando últimas notícias…", ru: "Загрузка последних новостей…", ja: "最新ニュースを読み込み中…" },

  // ── Homepage: Case Studies ──────────────────────────────────
  "home.caseStudies":      { en: "Case Studies",     zh: "案例研究",      hi: "केस स्टडी",       es: "Casos de estudio", fr: "Études de cas",  ar: "دراسات الحالة",  bn: "কেস স্টাডি",     pt: "Estudos de caso", ru: "Кейсы",          ja: "事例紹介" },
  "home.caseStudiesDesc":  { en: "See how leading brands use Lumen's attention technology to transform their advertising performance.", zh: "了解领先品牌如何使用Lumen的注意力技术来提升广告效果。", hi: "देखें कि अग्रणी ब्रांड कैसे Lumen की अटेंशन तकनीक का उपयोग करके अपने विज्ञापन प्रदर्शन को बदल रहे हैं।", es: "Descubra cómo las marcas líderes usan la tecnología de atención de Lumen para transformar el rendimiento de su publicidad.", fr: "Découvrez comment les grandes marques utilisent la technologie d'attention de Lumen pour transformer leurs performances publicitaires.", ar: "اكتشف كيف تستخدم العلامات التجارية الرائدة تقنية الانتباه من Lumen لتحويل أداء إعلاناتها.", bn: "দেখুন কীভাবে শীর্ষ ব্র্যান্ডগুলি তাদের বিজ্ঞাপন কর্মক্ষমতা রূপান্তর করতে Lumen-এর অ্যাটেনশন প্রযুক্তি ব্যবহার করে।", pt: "Veja como as marcas líderes usam a tecnologia de atenção da Lumen para transformar o desempenho de sua publicidade.", ru: "Узнайте, как ведущие бренды используют технологию внимания Lumen для трансформации эффективности рекламы.", ja: "主要ブランドがLumenのアテンション技術を活用して広告パフォーマンスをどのように変革しているかをご覧ください。" },
  "home.viewAllCaseStudies": { en: "View All Case Studies", zh: "查看所有案例研究", hi: "सभी केस स्टडी देखें", es: "Ver todos los casos", fr: "Voir toutes les études", ar: "عرض جميع دراسات الحالة", bn: "সমস্ত কেস স্টাডি দেখুন", pt: "Ver todos os estudos", ru: "Все кейсы", ja: "すべての事例を見る" },
  "home.loadingCaseStudies": { en: "Loading case studies…", zh: "正在加载案例研究…", hi: "केस स्टडी लोड हो रहे हैं…", es: "Cargando casos de estudio…", fr: "Chargement des études de cas…", ar: "جارٍ تحميل دراسات الحالة…", bn: "কেস স্টাডি লোড হচ্ছে…", pt: "Carregando estudos de caso…", ru: "Загрузка кейсов…", ja: "事例を読み込み中…" },

  // ── Homepage: FAQs ──────────────────────────────────────────
  "home.faqsTitle":        { en: "Frequently Asked Questions", zh: "常见问题", hi: "अक्सर पूछे जाने वाले प्रश्न", es: "Preguntas frecuentes", fr: "Questions fréquentes", ar: "الأسئلة الشائعة", bn: "প্রায়শই জিজ্ঞাসিত প্রশ্ন", pt: "Perguntas frequentes", ru: "Часто задаваемые вопросы", ja: "よくある質問" },
  "home.faqsSubtitle":     { en: "Everything you need to know about Lumen's attention measurement platform", zh: "您需要了解的关于Lumen注意力测量平台的一切", hi: "Lumen के अटेंशन मेजरमेंट प्लेटफॉर्म के बारे में वह सब कुछ जो आपको जानना चाहिए", es: "Todo lo que necesita saber sobre la plataforma de medición de atención de Lumen", fr: "Tout ce que vous devez savoir sur la plateforme de mesure de l'attention de Lumen", ar: "كل ما تحتاج معرفته عن منصة Lumen لقياس الانتباه", bn: "Lumen-এর অ্যাটেনশন মেজারমেন্ট প্ল্যাটফর্ম সম্পর্কে আপনার যা জানা দরকার", pt: "Tudo o que você precisa saber sobre a plataforma de medição de atenção da Lumen", ru: "Всё, что нужно знать о платформе измерения внимания Lumen", ja: "Lumenのアテンション測定プラットフォームについて知っておくべきすべてのこと" },

  "home.faq1Q": { en: "What is predictive eye-tracking?", zh: "什么是预测性眼动追踪？", hi: "प्रेडिक्टिव आई-ट्रैकिंग क्या है？", es: "¿Qué es el seguimiento ocular predictivo?", fr: "Qu'est-ce que le suivi oculaire prédictif ?", ar: "ما هو تتبع العين التنبؤي؟", bn: "প্রেডিক্টিভ আই-ট্র্যাকিং কী?", pt: "O que é rastreamento ocular preditivo?", ru: "Что такое предиктивное отслеживание взгляда?", ja: "予測的アイトラッキングとは？" },
  "home.faq1A": { en: "Eye-tracking technology captures gaze data from opt-in panels via front-facing cameras and browser extensions. AI models trained on 750K+ real-world sessions and 1B+ impressions predict where people look on any content. No images are stored — just gaze points and viewing behaviour. This allows us to measure attention at scale across 50+ countries.", zh: "预测性眼动追踪使用在数百万真实眼动追踪数据点上训练的AI模型来预测人们在任何内容上的注视位置。这使我们能够在不需要硬件或面板的情况下大规模测量注意力。", hi: "प्रेडिक्टिव आई-ट्रैकिंग लाखों वास्तविक आई-ट्रैकिंग डेटा पॉइंट पर प्रशिक्षित AI मॉडल का उपयोग करता है ताकि यह भविष्यवाणी कर सके कि लोग किसी भी सामग्री पर कहाँ देखेंगे। यह हमें हार्डवेयर या पैनल की आवश्यकता के बिना बड़े पैमाने पर ध्यान मापने की अनुमति देता है।", es: "El seguimiento ocular predictivo utiliza modelos de IA entrenados con millones de datos reales de seguimiento ocular para predecir dónde mirarán las personas en cualquier contenido. Esto nos permite medir la atención a escala sin necesidad de hardware o paneles.", fr: "Le suivi oculaire prédictif utilise des modèles d'IA entraînés sur des millions de données réelles de suivi oculaire pour prédire où les gens regarderont sur n'importe quel contenu. Cela nous permet de mesurer l'attention à grande échelle sans matériel ni panels.", ar: "يستخدم تتبع العين التنبؤي نماذج ذكاء اصطناعي مُدرَّبة على ملايين نقاط بيانات تتبع العين الحقيقية للتنبؤ بالمكان الذي سينظر إليه الناس في أي محتوى. وهذا يتيح لنا قياس الانتباه على نطاق واسع دون الحاجة إلى أجهزة أو لوحات.", bn: "প্রেডিক্টিভ আই-ট্র্যাকিং লক্ষ লক্ষ বাস্তব আই-ট্র্যাকিং ডেটা পয়েন্টে প্রশিক্ষিত AI মডেল ব্যবহার করে যেকোনো বিষয়বস্তুতে মানুষ কোথায় তাকাবে তা পূর্বাভাস দেয়। এটি হার্ডওয়্যার বা প্যানেল ছাড়াই বৃহৎ পরিসরে মনোযোগ পরিমাপ করতে দেয়।", pt: "O rastreamento ocular preditivo usa modelos de IA treinados em milhões de dados reais de rastreamento ocular para prever onde as pessoas olharão em qualquer conteúdo. Isso nos permite medir a atenção em escala sem necessidade de hardware ou painéis.", ru: "Предиктивное отслеживание взгляда использует модели ИИ, обученные на миллионах реальных данных отслеживания взгляда, чтобы предсказать, куда люди будут смотреть на любом контенте. Это позволяет нам измерять внимание в масштабе без необходимости в оборудовании или панелях.", ja: "予測的アイトラッキングは、何百万もの実際のアイトラッキングデータポイントで訓練されたAIモデルを使用して、あらゆるコンテンツ上で人々がどこを見るかを予測します。これにより、ハードウェアやパネルなしで大規模にアテンションを測定できます。" },

  "home.faq2Q": { en: "How accurate is Lumen's attention measurement?", zh: "Lumen的注意力测量有多准确？", hi: "Lumen का अटेंशन मेजरमेंट कितना सटीक है？", es: "¿Qué tan precisa es la medición de atención de Lumen?", fr: "Quelle est la précision de la mesure d'attention de Lumen ?", ar: "ما مدى دقة قياس الانتباه من Lumen؟", bn: "Lumen-এর অ্যাটেনশন মেজারমেন্ট কতটা সঠিক?", pt: "Quão precisa é a medição de atenção da Lumen?", ru: "Насколько точно измерение внимания Lumen?", ja: "Lumenのアテンション測定はどの程度正確ですか？" },
  "home.faq2A": { en: "Our predictive models achieve over 90% correlation (R² of 92.85%) with actual eye-tracking studies across 50+ countries. We continuously validate against real-world data from 750K+ consented sessions and 3K continuous panellists, retaining around 50-60% of data to ensure high quality.", zh: "我们的预测模型与实际眼动追踪研究的相关性超过90%。我们持续根据真实世界的眼动追踪数据验证和改进我们的模型。", hi: "हमारे प्रेडिक्टिव मॉडल वास्तविक आई-ट्रैकिंग अध्ययनों के साथ 90% से अधिक सहसंबंध प्राप्त करते हैं। हम वास्तविक दुनिया के आई-ट्रैकिंग डेटा के खिलाफ अपने मॉडल को लगातार मान्य और सुधारते रहते हैं।", es: "Nuestros modelos predictivos logran más del 90% de correlación con estudios reales de seguimiento ocular. Validamos y mejoramos continuamente nuestros modelos con datos reales.", fr: "Nos modèles prédictifs atteignent plus de 90% de corrélation avec les études réelles de suivi oculaire. Nous validons et améliorons continuellement nos modèles avec des données réelles.", ar: "تحقق نماذجنا التنبؤية ارتباطًا يزيد عن 90% مع دراسات تتبع العين الفعلية. نحن نتحقق باستمرار من نماذجنا ونحسّنها مقابل بيانات تتبع العين الحقيقية.", bn: "আমাদের পূর্বাভাসমূলক মডেলগুলি প্রকৃত আই-ট্র্যাকিং গবেষণার সাথে 90%-এর বেশি পারস্পরিক সম্পর্ক অর্জন করে। আমরা ক্রমাগত বাস্তব-বিশ্বের আই-ট্র্যাকিং ডেটার বিপরীতে আমাদের মডেলগুলিকে যাচাই ও উন্নত করি।", pt: "Nossos modelos preditivos alcançam mais de 90% de correlação com estudos reais de rastreamento ocular. Validamos e melhoramos continuamente nossos modelos com dados do mundo real.", ru: "Наши предиктивные модели достигают более 90% корреляции с реальными исследованиями отслеживания взгляда. Мы постоянно проверяем и совершенствуем наши модели на реальных данных.", ja: "当社の予測モデルは、実際のアイトラッキング調査との相関が90%以上を達成しています。実世界のアイトラッキングデータに基づいてモデルを継続的に検証・改善しています。" },

  "home.faq3Q": { en: "What channels can you measure?", zh: "你们可以测量哪些渠道？", hi: "आप किन चैनलों को माप सकते हैं？", es: "¿Qué canales pueden medir?", fr: "Quels canaux pouvez-vous mesurer ?", ar: "ما القنوات التي يمكنكم قياسها؟", bn: "আপনি কোন চ্যানেলগুলি পরিমাপ করতে পারেন?", pt: "Quais canais vocês podem medir?", ru: "Какие каналы вы можете измерять?", ja: "どのチャネルを測定できますか？" },
  "home.faq3A": { en: "We measure attention across all major channels: digital display and video, linear TV, CTV/VoD, social media, OOH/DOOH, cinema, print, packaging, audio, gaming, email, and retail media.", zh: "我们测量所有主要广告渠道的注意力，包括数字展示、视频、社交媒体、CTV、线性电视、户外、印刷和包装。", hi: "हम डिजिटल डिस्प्ले, वीडियो, सोशल मीडिया, CTV, लीनियर TV, आउट-ऑफ-होम, प्रिंट और पैकेजिंग सहित सभी प्रमुख विज्ञापन चैनलों में ध्यान मापते हैं।", es: "Medimos la atención en todos los canales publicitarios principales, incluidos display digital, video, redes sociales, CTV, TV lineal, exterior, impresión y empaque.", fr: "Nous mesurons l'attention sur tous les principaux canaux publicitaires, y compris l'affichage numérique, la vidéo, les réseaux sociaux, la CTV, la TV linéaire, l'affichage extérieur, l'impression et l'emballage.", ar: "نقيس الانتباه عبر جميع قنوات الإعلان الرئيسية بما في ذلك العرض الرقمي والفيديو ووسائل التواصل الاجتماعي وCTV والتلفزيون الخطي والإعلانات الخارجية والمطبوعات والتغليف.", bn: "আমরা ডিজিটাল ডিসপ্লে, ভিডিও, সোশ্যাল মিডিয়া, CTV, লিনিয়ার TV, আউট-অফ-হোম, প্রিন্ট এবং প্যাকেজিং সহ সমস্ত প্রধান বিজ্ঞাপন চ্যানেল জুড়ে মনোযোগ পরিমাপ করি।", pt: "Medimos a atenção em todos os principais canais de publicidade, incluindo display digital, vídeo, mídias sociais, CTV, TV linear, mídia exterior, impressão e embalagem.", ru: "Мы измеряем внимание по всем основным рекламным каналам, включая цифровую медийную рекламу, видео, социальные сети, CTV, линейное ТВ, наружную рекламу, печать и упаковку.", ja: "デジタルディスプレイ、動画、ソーシャルメディア、CTV、リニアTV、屋外広告、印刷、パッケージなど、すべての主要な広告チャネルでアテンションを測定しています。" },

  "home.faq4Q": { en: "How long does it take to get results?", zh: "获取结果需要多长时间？", hi: "परिणाम प्राप्त करने में कितना समय लगता है？", es: "¿Cuánto tiempo tardan los resultados?", fr: "Combien de temps faut-il pour obtenir les résultats ?", ar: "كم من الوقت يستغرق الحصول على النتائج؟", bn: "ফলাফল পেতে কতক্ষণ সময় লাগে?", pt: "Quanto tempo leva para obter resultados?", ru: "Сколько времени нужно для получения результатов?", ja: "結果が出るまでどのくらいかかりますか？" },
  "home.faq4A": { en: "Results are typically available within 24-48 hours of uploading your creative. For ongoing campaign measurement, data is updated in real-time.", zh: "上传创意后，结果通常在24-48小时内可用。对于持续的广告活动测量，数据实时更新。", hi: "आपकी क्रिएटिव अपलोड करने के 24-48 घंटे के भीतर परिणाम आम तौर पर उपलब्ध होते हैं। चल रहे अभियान मापन के लिए, डेटा वास्तविक समय में अपडेट किया जाता है।", es: "Los resultados suelen estar disponibles dentro de las 24-48 horas posteriores a la carga de su creatividad. Para la medición continua de campañas, los datos se actualizan en tiempo real.", fr: "Les résultats sont généralement disponibles dans les 24 à 48 heures suivant le téléchargement de votre créatif. Pour la mesure continue des campagnes, les données sont mises à jour en temps réel.", ar: "تتوفر النتائج عادةً خلال 24-48 ساعة من تحميل إبداعك. بالنسبة لقياس الحملات المستمرة، يتم تحديث البيانات في الوقت الفعلي.", bn: "আপনার ক্রিয়েটিভ আপলোড করার ২৪-৪৮ ঘণ্টার মধ্যে সাধারণত ফলাফল পাওয়া যায়। চলমান প্রচারাভিযان পরিমাপের জন্য, ডেটা রিয়েল-টাইমে আপডেট হয়।", pt: "Os resultados geralmente ficam disponíveis dentro de 24-48 horas após o upload do seu criativo. Para medição contínua de campanhas, os dados são atualizados em tempo real.", ru: "Результаты обычно доступны в течение 24-48 часов после загрузки креатива. Для текущих кампаний данные обновляются в реальном времени.", ja: "クリエイティブのアップロード後、通常24〜48時間以内に結果が利用可能になります。継続的なキャンペーン測定では、データはリアルタイムで更新されます。" },

  "home.faq5Q": { en: "Can I compare my results to industry benchmarks?", zh: "我可以将结果与行业基准进行比较吗？", hi: "क्या मैं अपने परिणामों की तुलना उद्योग बेंचमार्क से कर सकता हूं？", es: "¿Puedo comparar mis resultados con benchmarks de la industria?", fr: "Puis-je comparer mes résultats aux benchmarks du secteur ?", ar: "هل يمكنني مقارنة نتائجي بمعايير الصناعة؟", bn: "আমি কি আমার ফলাফলগুলি শিল্প বেঞ্চমার্কের সাথে তুলনা করতে পারি?", pt: "Posso comparar meus resultados com benchmarks do setor?", ru: "Могу ли я сравнить свои результаты с отраслевыми бенчмарками?", ja: "業界ベンチマークと結果を比較できますか？" },
  "home.faq5A": { en: "Yes! Our platform includes comprehensive benchmarks across industries, channels, and ad formats so you can see how your campaigns perform relative to others.", zh: "是的！我们的平台包含跨行业、渠道和广告格式的全面基准，让您可以看到您的广告活动相对于其他广告的表现。", hi: "हां! हमारे प्लेटफॉर्म में उद्योगों, चैनलों और विज्ञापन प्रारूपों में व्यापक बेंचमार्क शामिल हैं ताकि आप देख सकें कि आपके अभियान दूसरों की तुलना में कैसा प्रदर्शन करते हैं।", es: "¡Sí! Nuestra plataforma incluye benchmarks completos en todas las industrias, canales y formatos publicitarios para que pueda ver el rendimiento de sus campañas en comparación con otros.", fr: "Oui ! Notre plateforme inclut des benchmarks complets dans tous les secteurs, canaux et formats publicitaires afin que vous puissiez voir comment vos campagnes se comparent aux autres.", ar: "نعم! تتضمن منصتنا معايير شاملة عبر الصناعات والقنوات وأشكال الإعلانات حتى تتمكن من رؤية أداء حملاتك مقارنةً بالآخرين.", bn: "হ্যাঁ! আমাদের প্ল্যাটফর্মে শিল্প, চ্যানেল এবং বিজ্ঞাপন ফরম্যাট জুড়ে ব্যাপক বেঞ্চমার্ক রয়েছে যাতে আপনি দেখতে পারেন আপনার প্রচারাভিযানগুলি অন্যদের তুলনায় কেমন পারফর্ম করছে।", pt: "Sim! Nossa plataforma inclui benchmarks abrangentes em setores, canais e formatos de anúncios para que você possa ver como suas campanhas se comparam com outras.", ru: "Да! Наша платформа включает комплексные бенчмарки по отраслям, каналам и форматам рекламы, чтобы вы могли видеть, как ваши кампании работают по сравнению с другими.", ja: "はい！当社のプラットフォームには、業界、チャネル、広告フォーマットにわたる包括的なベンチマークが含まれており、キャンペーンの相対的なパフォーマンスを確認できます。" },

  "home.faq6Q": { en: "How do I get started?", zh: "我该如何开始？", hi: "मैं कैसे शुरू करूं？", es: "¿Cómo puedo empezar?", fr: "Comment commencer ?", ar: "كيف أبدأ؟", bn: "আমি কীভাবে শুরু করব?", pt: "Como começar?", ru: "Как начать?", ja: "どうすれば始められますか？" },
  "home.faq6A": { en: "Simply contact our team to schedule a demo. We'll walk you through the platform and help you set up your first attention measurement study.", zh: "只需联系我们的团队安排演示。我们将引导您了解平台并帮助您设置第一个注意力测量研究。", hi: "बस एक डेमो शेड्यूल करने के लिए हमारी टीम से संपर्क करें। हम आपको प्लेटफॉर्म के बारे में बताएंगे और आपको अपना पहला अटेंशन मेजरमेंट अध्ययन सेट अप करने में मदद करेंगे।", es: "Simplemente contacte a nuestro equipo para programar una demostración. Le guiaremos por la plataforma y le ayudaremos a configurar su primer estudio de medición de atención.", fr: "Contactez simplement notre équipe pour planifier une démonstration. Nous vous guiderons à travers la plateforme et vous aiderons à mettre en place votre première étude de mesure de l'attention.", ar: "ببساطة تواصل مع فريقنا لجدولة عرض توضيحي. سنرشدك عبر المنصة ونساعدك في إعداد أول دراسة لقياس الانتباه.", bn: "শুধু একটি ডেমো শিডিউল করতে আমাদের টিমের সাথে যোগাযোগ করুন। আমরা আপনাকে প্ল্যাটফর্মের মাধ্যমে গাইড করব এবং আপনার প্রথম অ্যাটেনশন মেজারমেন্ট স্টাডি সেট আপ করতে সাহায্য করব।", pt: "Basta entrar em contato com nossa equipe para agendar uma demonstração. Nós guiaremos você pela plataforma e ajudaremos a configurar seu primeiro estudo de medição de atenção.", ru: "Просто свяжитесь с нашей командой, чтобы запланировать демонстрацию. Мы проведём вас по платформе и поможем настроить первое исследование измерения внимания.", ja: "デモのスケジュールについては、お気軽にチームまでお問い合わせください。プラットフォームをご案内し、最初のアテンション測定調査の設定をお手伝いいたします。" },

  // ── Homepage: Contact Section ───────────────────────────────
  "home.contactTitle":     { en: "Ready to Transform Your Advertising?", zh: "准备好转变您的广告了吗？", hi: "क्या आप अपने विज्ञापन को बदलने के लिए तैयार हैं？", es: "¿Listo para transformar su publicidad?", fr: "Prêt à transformer votre publicité ?", ar: "هل أنت مستعد لتحويل إعلاناتك؟", bn: "আপনার বিজ্ঞাপন রূপান্তর করতে প্রস্তুত?", pt: "Pronto para transformar sua publicidade?", ru: "Готовы трансформировать свою рекламу?", ja: "広告を変革する準備はできていますか？" },
  "home.contactDesc":      { en: "Get in touch with our team to learn how Lumen can help you measure and optimize attention across all your advertising channels.", zh: "联系我们的团队，了解Lumen如何帮助您在所有广告渠道中测量和优化注意力。", hi: "हमारी टीम से संपर्क करें और जानें कि Lumen आपके सभी विज्ञापन चैनलों में ध्यान को मापने और अनुकूलित करने में कैसे मदद कर सकता है।", es: "Póngase en contacto con nuestro equipo para saber cómo Lumen puede ayudarle a medir y optimizar la atención en todos sus canales publicitarios.", fr: "Contactez notre équipe pour découvrir comment Lumen peut vous aider à mesurer et optimiser l'attention sur tous vos canaux publicitaires.", ar: "تواصل مع فريقنا لمعرفة كيف يمكن لـ Lumen مساعدتك في قياس وتحسين الانتباه عبر جميع قنواتك الإعلانية.", bn: "আমাদের টিমের সাথে যোগাযোগ করুন এবং জানুন কীভাবে Lumen আপনার সমস্ত বিজ্ঞাপন চ্যানেল জুড়ে মনোযোগ পরিমাপ ও অপ্টিমাইজ করতে সাহায্য করতে পারে।", pt: "Entre em contato com nossa equipe para saber como a Lumen pode ajudá-lo a medir e otimizar a atenção em todos os seus canais de publicidade.", ru: "Свяжитесь с нашей командой, чтобы узнать, как Lumen может помочь вам измерять и оптимизировать внимание по всем рекламным каналам.", ja: "Lumenがすべての広告チャネルにわたるアテンションの測定と最適化をどのように支援できるかについては、チームまでお問い合わせください。" },
  "home.sendUsMessage":    { en: "Send us a message",  zh: "给我们留言",     hi: "हमें संदेश भेजें",  es: "Envíenos un mensaje", fr: "Envoyez-nous un message", ar: "أرسل لنا رسالة", bn: "আমাদের একটি বার্তা পাঠান", pt: "Envie-nos uma mensagem", ru: "Отправьте нам сообщение", ja: "メッセージを送る" },
  "home.formName":         { en: "Name",             zh: "姓名",          hi: "नाम",            es: "Nombre",          fr: "Nom",             ar: "الاسم",          bn: "নাম",            pt: "Nome",           ru: "Имя",            ja: "お名前" },
  "home.formEmail":        { en: "Email",            zh: "电子邮件",       hi: "ईमेल",           es: "Correo electrónico", fr: "E-mail",        ar: "البريد الإلكتروني", bn: "ইমেইল",        pt: "E-mail",         ru: "Электронная почта", ja: "メールアドレス" },
  "home.formCompany":      { en: "Company",          zh: "公司",          hi: "कंपनी",          es: "Empresa",         fr: "Entreprise",      ar: "الشركة",         bn: "কোম্পানি",       pt: "Empresa",        ru: "Компания",       ja: "会社名" },
  "home.formMessage":      { en: "Message",          zh: "消息",          hi: "संदेश",           es: "Mensaje",         fr: "Message",         ar: "الرسالة",        bn: "বার্তা",          pt: "Mensagem",       ru: "Сообщение",      ja: "メッセージ" },
  "home.formNamePlaceholder":    { en: "Your name",         zh: "您的姓名",       hi: "आपका नाम",       es: "Su nombre",       fr: "Votre nom",       ar: "اسمك",           bn: "আপনার নাম",      pt: "Seu nome",       ru: "Ваше имя",       ja: "お名前" },
  "home.formEmailPlaceholder":   { en: "you@company.com",   zh: "you@company.com", hi: "you@company.com", es: "tu@empresa.com",  fr: "vous@entreprise.com", ar: "you@company.com", bn: "you@company.com", pt: "voce@empresa.com", ru: "you@company.com", ja: "you@company.com" },
  "home.formCompanyPlaceholder": { en: "Your company",      zh: "您的公司",       hi: "आपकी कंपनी",      es: "Su empresa",      fr: "Votre entreprise", ar: "شركتك",          bn: "আপনার কোম্পানি",  pt: "Sua empresa",    ru: "Ваша компания",  ja: "会社名" },
  "home.formMessagePlaceholder": { en: "Tell us about your advertising measurement needs...", zh: "告诉我们您的广告测量需求...", hi: "अपनी विज्ञापन मापन आवश्यकताओं के बारे में बताएं...", es: "Cuéntenos sobre sus necesidades de medición publicitaria...", fr: "Parlez-nous de vos besoins en mesure publicitaire...", ar: "أخبرنا عن احتياجاتك في قياس الإعلانات...", bn: "আপনার বিজ্ঞাপন পরিমাপের চাহিদা সম্পর্কে আমাদের বলুন...", pt: "Conte-nos sobre suas necessidades de medição publicitária...", ru: "Расскажите о ваших потребностях в измерении рекламы...", ja: "広告測定のニーズについてお聞かせください..." },
  "home.sendMessage":      { en: "Send Message",     zh: "发送消息",       hi: "संदेश भेजें",     es: "Enviar mensaje",  fr: "Envoyer le message", ar: "إرسال الرسالة",  bn: "বার্তা পাঠান",    pt: "Enviar mensagem", ru: "Отправить",       ja: "メッセージを送信" },

  // ── Latest News Section ──────────────────────────────────────
  "news.stayUpdated":      { en: "Read the latest insights from advertisers using attention to shape their business", zh: "阅读广告商利用注意力塑造业务的最新洞察", hi: "ध्यान का उपयोग करके अपने व्यवसाय को आकार देने वाले विज्ञापनदाताओं की नवीनतम अंतर्दृष्टि पढ़ें", es: "Lea las últimas perspectivas de anunciantes que usan la atención para transformar su negocio", fr: "Découvrez les dernières perspectives des annonceurs qui utilisent l'attention pour façonner leur activité", ar: "اقرأ أحدث الرؤى من المعلنين الذين يستخدمون الانتباه لتشكيل أعمالهم", bn: "মনোযোগ ব্যবহার করে ব্যবসা গঠনকারী বিজ্ঞাপনদাতাদের সর্বশেষ অন্তর্দৃষ্টি পড়ুন", pt: "Leia os últimos insights de anunciantes que usam a atenção para moldar seus negócios", ru: "Читайте последние материалы от рекламодателей, использующих внимание для развития бизнеса", ja: "アテンションを活用してビジネスを形成する広告主の最新インサイトをお読みください" },
  "news.checkBack":        { en: "Check back soon for news and updates.", zh: "请稍后查看新闻和更新。", hi: "समाचार और अपडेट के लिए जल्द ही वापस आएं।", es: "Vuelva pronto para noticias y actualizaciones.", fr: "Revenez bientôt pour des nouvelles et mises à jour.", ar: "تحقق مرة أخرى قريبًا للحصول على الأخبار والتحديثات.", bn: "সংবাদ ও আপডেটের জন্য শীঘ্রই আবার দেখুন।", pt: "Volte em breve para novidades e atualizações.", ru: "Заходите снова за новостями и обновлениями.", ja: "ニュースとアップデートをお楽しみに。" },
  "news.viewAll":          { en: "View All News", zh: "查看所有新闻", hi: "सभी समाचार देखें", es: "Ver todas las noticias", fr: "Voir toutes les actualités", ar: "عرض جميع الأخبار", bn: "সমস্ত সংবাদ দেখুন", pt: "Ver todas as notícias", ru: "Все новости", ja: "すべてのニュースを見る" },

  // ── For Advertisers & For Agencies ─────────────────────────
  "lmc.forAdvertisers":    { en: "For Advertisers", zh: "面向广告商", hi: "विज्ञापनदाताओं के लिए", es: "Para Anunciantes", fr: "Pour les Annonceurs", ar: "للمعلنين", bn: "বিজ্ঞাপনদাতাদের জন্য", pt: "Para Anunciantes", ru: "Для рекламодателей", ja: "広告主向け" },
  "lmc.forAdvertisersPrefix": { en: "For", zh: "面向", hi: "के लिए", es: "Para", fr: "Pour les", ar: "لـ", bn: "জন্য", pt: "Para", ru: "Для", ja: "" },
  "lmc.forAdvertisersSuffix": { en: "Advertisers", zh: "广告商", hi: "विज्ञापनदाता", es: "Anunciantes", fr: "Annonceurs", ar: "المعلنين", bn: "বিজ্ঞাপনদাতা", pt: "Anunciantes", ru: "рекламодателей", ja: "広告主向け" },
  "lmc.advertisersHeadline": { en: "Maximise the impact of every impression", zh: "最大化每次曝光的影响", hi: "हर इंप्रेशन के प्रभाव को अधिकतम करें", es: "Maximice el impacto de cada impresión", fr: "Maximisez l'impact de chaque impression", ar: "عظّم تأثير كل ظهور", bn: "প্রতিটি ইম্প্রেশনের প্রভাব সর্বাধিক করুন", pt: "Maximize o impacto de cada impressão", ru: "Максимизируйте эффект каждого показа", ja: "すべてのインプレッションの効果を最大化" },
  "lmc.advertisersDesc":   { en: "Use attention data to understand what your audience actually sees, optimise creative performance, and prove the value of your media investments.", zh: "利用注意力数据了解受众实际看到的内容，优化创意表现，并证明媒体投资的价值。", hi: "ध्यान डेटा का उपयोग करके जानें कि आपके दर्शक वास्तव में क्या देखते हैं, क्रिएटिव प्रदर्शन को अनुकूलित करें, और अपने मीडिया निवेश का मूल्य साबित करें।", es: "Use datos de atención para entender lo que su audiencia realmente ve, optimice el rendimiento creativo y demuestre el valor de sus inversiones en medios.", fr: "Utilisez les données d'attention pour comprendre ce que votre audience voit réellement, optimisez les performances créatives et prouvez la valeur de vos investissements médias.", ar: "استخدم بيانات الانتباه لفهم ما يراه جمهورك فعليًا، وحسّن أداء الإبداعات، وأثبت قيمة استثماراتك الإعلامية.", bn: "অ্যাটেনশন ডেটা ব্যবহার করে জানুন আপনার দর্শকরা আসলে কী দেখে, ক্রিয়েটিভ পারফরম্যান্স অপ্টিমাইজ করুন এবং মিডিয়া বিনিয়োগের মূল্য প্রমাণ করুন।", pt: "Use dados de atenção para entender o que seu público realmente vê, otimize o desempenho criativo e comprove o valor dos seus investimentos em mídia.", ru: "Используйте данные о внимании, чтобы понять, что на самом деле видит ваша аудитория, оптимизируйте креативы и докажите ценность медиа-инвестиций.", ja: "アテンションデータを使って、オーディエンスが実際に何を見ているかを理解し、クリエイティブパフォーマンスを最適化し、メディア投資の価値を証明します。" },
  "lmc.forAgencies":       { en: "For Agencies", zh: "面向代理商", hi: "एजेंसियों के लिए", es: "Para Agencias", fr: "Pour les Agences", ar: "للوكالات", bn: "এজেন্সিদের জন্য", pt: "Para Agências", ru: "Для агентств", ja: "エージェンシー向け" },
  "lmc.forAgenciesPrefix": { en: "For", zh: "面向", hi: "के लिए", es: "Para", fr: "Pour les", ar: "لـ", bn: "জন্য", pt: "Para", ru: "Для", ja: "" },
  "lmc.forAgenciesSuffix": { en: "Agencies", zh: "代理商", hi: "एजेंसियाँ", es: "Agencias", fr: "Agences", ar: "الوكالات", bn: "এজেন্সি", pt: "Agências", ru: "агентств", ja: "エージェンシー向け" },
  "lmc.agenciesHeadline":  { en: "Deliver attention-optimised campaigns at scale", zh: "大规模交付注意力优化的广告活动", hi: "बड़े पैमाने पर ध्यान-अनुकूलित अभियान वितरित करें", es: "Entregue campañas optimizadas por atención a escala", fr: "Livrez des campagnes optimisées par l'attention à grande échelle", ar: "قدّم حملات محسّنة للانتباه على نطاق واسع", bn: "বৃহৎ পরিসরে অ্যাটেনশন-অপ্টিমাইজড ক্যাম্পেইন ডেলিভার করুন", pt: "Entregue campanhas otimizadas por atenção em escala", ru: "Проводите кампании, оптимизированные по вниманию, в масштабе", ja: "アテンション最適化キャンペーンを大規模に展開" },
  "lmc.agenciesDesc":      { en: "Plan, buy, and measure media with attention metrics built in. Give your clients a competitive edge with data-driven attention strategies.", zh: "将注意力指标内置到媒体规划、购买和测量中。通过数据驱动的注意力策略为客户提供竞争优势。", hi: "ध्यान मेट्रिक्स के साथ मीडिया की योजना बनाएं, खरीदें और मापें। डेटा-संचालित ध्यान रणनीतियों से अपने ग्राहकों को प्रतिस्पर्धात्मक बढ़त दें।", es: "Planifique, compre y mida medios con métricas de atención integradas. Dé a sus clientes una ventaja competitiva con estrategias de atención basadas en datos.", fr: "Planifiez, achetez et mesurez les médias avec des métriques d'attention intégrées. Offrez à vos clients un avantage concurrentiel grâce à des stratégies d'attention basées sur les données.", ar: "خطط واشترِ وقس الوسائط مع مقاييس انتباه مدمجة. امنح عملاءك ميزة تنافسية باستراتيجيات انتباه مبنية على البيانات.", bn: "অ্যাটেনশন মেট্রিক্স সহ মিডিয়া পরিকল্পনা, ক্রয় এবং পরিমাপ করুন। ডেটা-চালিত অ্যাটেনশন কৌশল দিয়ে আপনার ক্লায়েন্টদের প্রতিযোগিতামূলক সুবিধা দিন।", pt: "Planeje, compre e meça mídia com métricas de atenção integradas. Dê aos seus clientes uma vantagem competitiva com estratégias de atenção baseadas em dados.", ru: "Планируйте, покупайте и измеряйте медиа со встроенными метриками внимания. Дайте клиентам конкурентное преимущество с помощью стратегий на основе данных о внимании.", ja: "アテンション指標を組み込んだメディアの計画、購入、測定を行い、データドリブンなアテンション戦略でクライアントに競争優位をもたらします。" },

  // ── Language Switcher ───────────────────────────────────────
  "lang.switchLanguage":   { en: "Switch language",  zh: "切换语言",       hi: "भाषा बदलें",     es: "Cambiar idioma",  fr: "Changer de langue", ar: "تغيير اللغة",   bn: "ভাষা পরিবর্তন",   pt: "Mudar idioma",   ru: "Сменить язык",   ja: "言語を切り替え" },
};

export function t(language: LanguageCode, key: string): string {
  const entry = translations[key];
  if (!entry) return key;
  return entry[language] || entry.en || key;
}
